name: Tag Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        run: cargo build --release --verbose
      - name: Test
        run: cargo test --release --verbose
      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --verbose
      - name: Update GitHub Release with crates.io link
        uses: actions/github-script@v7
        with:
          script: |
            const tag = context.ref.replace('refs/tags/', '');
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const cratesUrl = `https://crates.io/crates/${repo}`;
            const releases = await github.rest.repos.listReleases({ owner, repo });
            const release = releases.data.find(r => r.tag_name === tag);
            if (release) {
              const newBody = (release.body || '') + `\n\nCrates.io release: ${cratesUrl}`;
              await github.rest.repos.updateRelease({
                owner,
                repo,
                release_id: release.id,
                body: newBody
              });
            }
